config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names:{sign_in: 'login',sign_out: 'logout'}
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
          patch :priority
        end
    end
  end
  root "todo_lists#index"
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  validates :content, length: {minimum: 3, too_short: "%{count} characters is the minimum allowed"}, presence: true

  belongs_to :todo_list



  def completed?
    !completed_at.blank?
  end

  def deadline?
    if deadline.present? && (Time.now() - deadline) < 0
      true
    else
      false
    end
  end
  def priority?
    if priority==0
      false
    else
      true
    end
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  validates :title, length: {minimum: 3}, presence: true
  belongs_to :user

  has_many :todo_items
  accepts_nested_attributes_for :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters,if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list,:set_todo_lists
  before_action :set_todo_item,except: [:create]
  def create
    @todo_item=@todo_list.todo_items.create(todo_item_params)
    respond_to do |format|
      format.html{redirect_to @todo_list,@todo_item}
      format.js
    end
  end

  def complete
    @todo_item.update_attribute(:completed_at,Time.now)
    respond_to do |format|
      format.html{ redirect_to @todo_list}
      format.js
    end
  end
  def priority
    if @todo_item.priority==0
    @todo_item.update_attribute(:priority,1)
    else
      @todo_item.update_attribute(:priority,0)
    end
    respond_to do |format|
      format.html{ redirect_to @todo_list}
      format.js
    end
  end
  def destroy
    @todo_item=@todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success]="Todo list item was deleted. "
    else
      flash[:error]="Todo list item could not be deleted."
    end
    respond_to do |format|
      format.html{ redirect_to @todo_list}
      format.js
    end
  end

  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list}
        format.js
      else
        format.html { render :edit }
        format.js

      end
    end
  end
  private

  def set_todo_lists
    @todo_lists = TodoList.where("user_id = ?",current_user.id)
  end
  def set_todo_list
    @todo_list=TodoList.find(params[:todo_list_id])
  end
  def set_todo_item
    @todo_item=@todo_list.todo_items.find(params[:id])

  end
  def todo_item_params
    params[:todo_item].permit(:content,:deadline)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :current_todo_list, only: [:show]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where("user_id = ?",current_user.id)

  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
    @todo_list.todo_items.build

  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list.todo_items.build
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user_id=current_user.id

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list}
        format.json { render :show, status: :created, location: @todo_list }
        format.js
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
        format.js

      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    @todo_id=@todo_list.id
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        @todo_lists = TodoList.where("user_id = ?",current_user.id)
        format.html { redirect_to @todo_list}
        format.json { render :show, status: :ok, location: @todo_list }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
        format.js

      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.todo_items.each do |todo_item|
      todo_item.destroy
    end
    @todo_list_id=@todo_list.id
    @todo_list.destroy
    @todo_lists = TodoList.where("user_id = ?",current_user.id)
    respond_to do |format|
      format.html { redirect_to root_url}
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description, todo_items_attributes: [:content])
    end

    def current_todo_list
      if @todo_list.user_id != current_user.id
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->

</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <%= link_to 'todo rubygarage', root_url, :class => 'navbar-brand  text-uppercase' %>

    <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to current_user.name, edit_user_registration_path, :class => '' %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => ''  %>
          </li>
        </ul>
    <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign up", new_user_registration_path, :class => ''  %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, :class => ''  %>
          </li>
        </ul>
    <% end %>
  </div>
</nav>
<div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build],remote: true) do |f| %>
    <%= f.text_field :content, placeholder: "New Todo" %>
     <%= f.text_field :deadline, placeholder: "Pick the date and time",class: "form-control", id: 'datetimepicker' %>

    <%= f.submit class: "create-todo-item" %>
<% end %>




<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datetimepicker({
            format: "YYYY-MM-DD HH:mm:ss.SSS"
        });
    });
</script>

app/views/todo_items/_todo_item.html.erb
<div id="todo_item_wrapper">
<div class="row row clearfix">
    <% if todo_item.completed? %>
      <div class="complete">
        <%= link_to complete_todo_list_todo_item_path(@todo_list,todo_item.id), method: :patch, remote: true do%>
        <i style="opacity: 0.4" class="fa fa-check"></i>
        <%	 end %>
      </div>
      <div class="todo_item">
        <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
      </div>
      <div class="trash">
        <%= link_to todo_list_todo_item_path(@todo_list,todo_item.id),method: :delete,remote: true do%>
       <i class="fa fa-trash"></i>
        <%	 end %>
      </div>
  <% else %>
      <div class="complete">
        <%= link_to complete_todo_list_todo_item_path(@todo_list,todo_item.id),method: :patch,remote: true do%>
            <i class="fa fa-check"></i>
        <%	 end %>
      </div>
      <div class="todo_item">
        <p><%= todo_item.content %></p>
      </div>
      <div class="trash">
        <%= link_to todo_list_todo_item_path(@todo_list,todo_item.id),method: :delete,remote: true do%>
            <i class="fa fa-trash"></i>
        <%	 end %>
      </div>
<% end %>
</div>
</div>

app/views/todo_items/complete.js.erb
$("#todo_list_id_<%= @todo_item.todo_list.id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_item.todo_list.id) )%>');
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

app/views/todo_items/create.js.erb
$("#todo_list_id_<%= @todo_item.todo_list.id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_item.todo_list.id) )%>');


$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

app/views/todo_items/destroy.js.erb
$("#todo_list_id_<%= @todo_item.todo_list.id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_item.todo_list.id) )%>');
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

app/views/todo_items/edit.html.erb
<p>hello</p>
<%= render 'form' %>

app/views/todo_items/priority.js.erb
$("#todo_list_id_<%= @todo_item.todo_list.id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_item.todo_list.id) )%>');
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

app/views/todo_items/update.js.erb
$('#myModalEditItem<%=@todo_item.id%>').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$("#todo_list_id_<%= @todo_item.todo_list.id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_item.todo_list.id) )%>');
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list, remote: true do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

        <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div class="index_row clearfix " id="todo_list_id_<%=todo_list.id%>">
  <div class="container-fluid title bg-primary">
            <div  class="row">
        <div class="col-md-8 ">
              <h2  class="todo_list_title"><span class="glyphicon glyphicon-calendar"></span>
                <%= todo_list.title %>

              </h2>
        </div>
            <div  class="col-md-2 col-md-offset-2 text-right" >
              <div class="trash">
                <h3>
                <%= link_to "#",id: "edit_todo_list","data-toggle" => "modal", "data-target" =>"#myModalEdit#{todo_list.id}",remote: true do%>
                    <i class="glyphicon glyphicon-pencil" ></i>
                <% end %>
                  |
                  <%= link_to todo_list_path(todo_list),remote: true,method: :delete do%>
                      <i class="glyphicon glyphicon-trash"></i>
                  <%	 end %>
                </h3>
            </div>
        </div>
            </div>
  </div>

<div class="row" style="margin-top: 15px; margin-bottom: 15px">
  <div class="col-md-12 " >
    <div class="form" style="width: 100%;">
    <form  class="new_todo_item form form-inline" id="new_todo_item" action="/todo_lists/<%=todo_list.id%>/todo_items" accept-charset="utf-8" data-remote="true" method="post">
      <span  class="">&nbsp;</span>
      <span  class="glyphicon glyphicon-plus"></span>
      <input name="utf8" type="hidden" value="?">
      <input class="form-control" placeholder="Start typing here to create a task" required="required" minlength="3" type="text" style="width: 80%" name="todo_item[content]" id="todo_item_content">
      <input type="submit" name="commit" value="Add Task" style="width: 15%" class="create-todo-item btn btn-default">
    </form>
    </div>
  </div>
</div>
  <div id="todo_items_wrapper_list" class="row">

      <% todo_list.todo_items.order(priority: :desc,created_at: :asc).each do |todo_item| %>
        <!-- Modal Edit Item-->
        <div class="modal fade bs-example-modal-lg" id="myModalEditItem<%= todo_item.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="forms">
                <form class="edit_todo_list_todo_item form" id="edit_todo_list_todo_item_<%= todo_item.id %>" action="/todo_lists/<%= todo_list.id %>/todo_items/<%= todo_item.id%>" accept-charset="UTF-8" data-remote="true" method="post">
                  <input name="utf8" type="hidden" value="?"><input type="hidden" name="_method" value="patch">
                  <div class="modal-body">
                    <div class="form-group">
                      <label for="todo_item_content">Content</label><br>
                      <input type="text" value="<%=todo_item.content %>" required="required" minlength="3" name="todo_item[content]" id="todo_item_content" style="width: 100%">

                    </div>
                    <div class="form-group">
                        <input type='text' class="form-control" id='datetimepicker<%=todo_item.id %>' name="todo_item[deadline]" value="<%= todo_item.deadline%>"/>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker<%= todo_item.id%>').datetimepicker({
                                format: "YYYY-MM-DD HH:mm:ss.SSS"

                            });
                        });
                    </script>


                  </div>
                  <div class="modal-footer">
                    <input type="submit" name="commit" class="btn btn-default" value="Update task" >
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

          <div id="todo_items_wrapper ">

            <div class="row" >
              <% if todo_item.completed? %>
                  <div class="col-md-1 ">
                      <div class="complete pull-right">
                            <i style="opacity: 0.4" class="glyphicon glyphicon-ok"></i>
                      </div>
                  </div>
                  <div class="col-md-8">
                      <div class="todo_item">
                        <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
                      </div>
                  </div>
                  <div class="col-md-1">
                    <p data-toggle="tooltip" data-placement="right" class="pull-right glyphicon glyphicon-calendar" title="
                      <% if todo_item.deadline.present? %>
                          <% if todo_item.deadline? %>
                              <%= distance_of_time_in_words(Time.now + 3.hours,todo_item.deadline)%> left to deadline
                          <% else %>
                                Deadline expired
                          <% end %>
                    <% else %>
                          No deadline
                      <% end %>
                      ">
                    </p>
                  </div>
                  <div class="col-md-2">
                  <div class="trash">
                    <%if todo_item.priority? %>
                        <%= link_to priority_todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :patch do%>
                            <i class="glyphicon glyphicon-star"></i>
                        <%	 end %>
                    <% else %>
                        <%= link_to priority_todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :patch do%>
                            <i class="glyphicon glyphicon-star-empty"></i>
                        <%	 end %>
                    <%end %>
                    <i> | </i>
                    <%= link_to "#",id: "edit_todo_list_todo_item","data-toggle" => "modal", "data-target" =>"#myModalEditItem#{todo_item.id}",remote: true  do%>
                        <i class="glyphicon glyphicon-pencil"></i>
                    <%	 end %>
                    <i> | </i>
                    <%= link_to todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :delete do%>
                        <i class="glyphicon glyphicon-trash"></i>
                    <%	 end %>
                  </div>
                  </div>
              <% else %>
                  <div class="col-md-1">
                  <div class="complete pull-right">
                    <%= link_to complete_todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :patch do%>
                        <i class="glyphicon glyphicon-ok"></i>
                    <%	 end %>
                  </div>
                    </div>
                  <div class="col-md-8">
                  <div class="todo_item">
                    <p><%= todo_item.content %> </p>
                  </div>
                    </div>
                  <div class="col-md-1">
                    <p data-placement="right" data-toggle="tooltip" class="pull-right glyphicon glyphicon-calendar"
                       title="<% if todo_item.deadline.present? %>
                          <% if todo_item.deadline? %>
                              <%= distance_of_time_in_words(Time.now + 3.hours,todo_item.deadline)%> left to deadline
                          <% else %>
                                Deadline expired
                          <% end %>
                    <% else %>
                    No deadline
                    <% end %>
                      ">
                    </p>
                  </div>
                  <div class="col-md-2">
                  <div class="trash" title="test">
                    <%if todo_item.priority? %>
                        <%= link_to priority_todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :patch do%>
                            <i class="glyphicon glyphicon-star"></i>
                        <%	 end %>
                    <% else %>
                        <%= link_to priority_todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :patch do%>
                            <i class="glyphicon glyphicon-star-empty"></i>
                        <%	 end %>
                        <%end %>
                    <i> | </i>
                    <%= link_to "#",id: "edit_todo_list_todo_item","data-toggle" => "modal", "data-target" =>"#myModalEditItem#{todo_item.id}",remote: true  do%>
                        <i class="glyphicon glyphicon-pencil"></i>
                        <%	 end %>
                    <i> | </i>
                    <%= link_to todo_list_todo_item_path(todo_list,todo_item.id),remote: true,method: :delete do%>
                        <i class="glyphicon glyphicon-trash"></i>
                    <%	 end %>
                  </div>
                  </div>
              <% end %>
            </div>

        </div>

      <% end %>
  </div>
</div>


<!-- Modal Edit-->
<div class="modal fade bs-example-modal-lg" id="myModalEdit<%= todo_list.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="forms">
        <form class="edit_todo_list form" id="edit_todo_list_<%= todo_list.id %>" action="/todo_lists/<%= todo_list.id %>" accept-charset="UTF-8" data-remote="true" method="post">
          <input name="utf8" type="hidden" value="?"><input type="hidden" name="_method" value="patch">
         <div class="modal-body">
          <div class="form-group">
            <label for="todo_list_title">Title</label><br>
            <input type="text" value="<%=todo_list.title %>" required="required" minlength="3" name="todo_list[title]" id="todo_list_title" style="width: 100%">
          </div>
         </div>
          <div class="modal-footer">
            <input type="submit" name="commit" class="btn btn-default" value="Update Todo list" >
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/create.js.erb
$('#myModal').modal('hide');
$('#todo_list_title').val("");
$('#todo_list_description').val("");
$('#todo_lists').append("<%= j (render @todo_list)%>");

app/views/todo_lists/destroy.js.erb
$("#todo_list_id_<%= @todo_list_id%>").remove();

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>
<div class="forms">
  <%= render 'form' %>
</div>
<div class="links">
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2" id="todo_lists">
    <%	 @todo_lists.each do |todo_list| %>
          <%= render todo_list%>
    <%	end  %>

  </div>
</div>
<div class="row">
  <div class="col-md-offset-5 text-center col-md-1">
  <button class="btn btn-primary" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-plus"></span> New project</button>
  </div>
</div>

<div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for TodoList.new, remote: true,class: "form", role:"form" do |f| %>
          <div class="modal-body">
    <div class="form-group">
              <%= f.label :title %><br>
              <%= f.text_field :title ,value: "", style: "width: 100%" %>
            </div>
          </div>
            <div class="modal-footer">
              <%= f.button type: 'submit' ,class: "btn btn-default" %>
            </div>

<% end %>
</div>
  </div>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
<%= render 'form' %>
</div>
<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="todo_list_title"><%=	@todo_list.title  %></h2>
<div id="todo_items_wrapper_list">
<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
</div>

</div>
<div id="form">
  <%= render "todo_items/form" %>
</div>
<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete %> |
   <%= link_to 'Back', todo_lists_path %>

</div>

app/views/todo_lists/update.js.erb
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
$('#myModalEdit<%=@todo_id%>').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$("#todo_list_id_<%= @todo_id%>").replaceWith('<%= j (  render @todo_lists.where("id= ?",@todo_id) )%>');